export class ProductDetailModel {
  constructor(
    public id: number,
    public productColorId: number,
    public createdAt: Date,
    public createdBy: number,
    public updatedAt: Date,
    public updatedBy: number,
    public bridgeWidth?: number,
    public frameWidth?: number,
    public lensHeight?: number,
    public lensWidth?: number,
    public templeLength?: number,
    public productNumber?: number,
    public frameMaterial?: string,
    public frameShape?: string,
    public frameType?: string,
    public bridgeDesign?: string,
    public style?: string,
    public springHinges: boolean = false,
    public weight?: number,
    public multifocal: boolean = false,
    public deletedAt?: Date,
    public deletedBy?: number,
  ) {}
}
