export class LensUpgradeDetailModel {
  constructor(
    public id: number,
    public name: string,
    public upgradeHardCoating: boolean,
    public upgradeAntiReflection: boolean,
    public upgradeUvProtection: boolean,
    public upgradeBlueLight: boolean,
    public upgradeLotusEffect: boolean,
    public upgradeSmartFocus: boolean,
    public upgradeTransition: boolean,
    public upgradeProgressive: boolean,
    public upgradeHardCoatingPrice: number,
    public upgradeAntiReflectionPrice: number,
    public upgradeUvProtectionPrice: number,
    public upgradeBluelightPrice: number,
    public upgradeLotusEffectPrice: number,
    public upgradeSmartFocusPrice: number,
    public upgradeTransitionPrice: number,
    public upgradeProgressivePrice: number,
    public totalUpgradesPrice: number,
    public description: string | undefined,
    public createdAt: Date,
    public createdBy: number | undefined,
    public updatedAt: Date,
    public updatedBy: number | undefined,
    public deletedAt: Date | undefined,
    public deletedBy: number | undefined,
  ) {}
}
